---
title: "Assignment 5"
author: "Mairi-Jo Musgrave, A00407737"
date: "15/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Article: 
Water delivery system effects on coliform bacteria in tap water in First Nations reserves in Manitoba, Canada.


## Reference 
Amarawansha, G. E. A., Zvomuya, F., & Farenhorst, A. (2021). Water delivery system effects on       coliform bacteria in tap water in First Nations reserves in Manitoba, Canada. Environmental      Monitoring and Assessment, 193(6), 1-16.


## Introduction
First nations reserves in Canada experience frequent drinking water advisories due to the presence of coliform bacteria. This article focuses on First Nations reserves in Manitoba, mainly because 50% of homes on these reserves do not have piped water from a water treatment plant, but rather have water brought in from a water treatment plant to local cisterns. Previous studies determined that treated water was more likely to have the presence of coliforms when taken from a cistern than if it had been piped directly from a water treatment plant. This is due to high turbidity in cisterns meaning the chlorine reacts with other chlorine, making it ineffective against microorganisms. Additionally, water can sit in cisterns for a long time before it is used, giving the chlorine more time to decay.  This paper looked at three different communities in Manitoba which used different types of cisterns. The objective of this paper was to determine how cisterns affect coliform levels in drinking water in camparison to piped water.

## Methods
Before undertaking any research, members of the research team met with leaders from all three communities to discuss logistics of data collection. A Resolution was drafted and signed by all parties. Members from the community worked with the research team to identify homes in which samples would be collected. For each period of sampling water was collected to test total coliforms and chlorine from the water supply, the water treatment plant, the delivery truck in instances of cistern use, and the tap water in community homes. Ten homes with piped water and ten homes with cistern water were tested. The research team tested two of the communities at three different times to account for temporal  differences in water quality. The third community was remote and could therefore only be tested once. In addition to samples collected by the research team, monthly samples of tap water were collected by the community, however these samples varied in number and distribution between communities.

## Results







